services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: ""
    startCommand: bash start.sh
    autoDeploy: false
    envVars:
      - key: TELEGRAM_TOKEN
        value: твой_токен_бота
      - key: GOOGLE_SHEET_NAME
        value: Ставки